// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLCQQqN0yMNltXXoICm2zXUpm7KKdfRk0',
    appId: '1:692147529807:web:026de38056d28fb8ee223a',
    messagingSenderId: '692147529807',
    projectId: 'shayriapp-5c7de',
    authDomain: 'shayriapp-5c7de.firebaseapp.com',
    storageBucket: 'shayriapp-5c7de.appspot.com',
    measurementId: 'G-3GLP8E38YL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ15b5HCNG8LumlQoW-DkQB9xEyw8ZQfQ',
    appId: '1:692147529807:android:ffff25996ce5f58cee223a',
    messagingSenderId: '692147529807',
    projectId: 'shayriapp-5c7de',
    storageBucket: 'shayriapp-5c7de.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8CWwmSe621R4whqQQ-5jXLTyqgiyGbTE',
    appId: '1:692147529807:ios:e690edf62f9fd12eee223a',
    messagingSenderId: '692147529807',
    projectId: 'shayriapp-5c7de',
    storageBucket: 'shayriapp-5c7de.appspot.com',
    iosBundleId: 'com.example.shayari',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLCQQqN0yMNltXXoICm2zXUpm7KKdfRk0',
    appId: '1:692147529807:web:a038d878d062bb39ee223a',
    messagingSenderId: '692147529807',
    projectId: 'shayriapp-5c7de',
    authDomain: 'shayriapp-5c7de.firebaseapp.com',
    storageBucket: 'shayriapp-5c7de.appspot.com',
    measurementId: 'G-4SRPXS6Y7Z',
  );
}
